CinemaApp/Controllers/MoviesController.cs
using CinemaApp.Data;
using CinemaApp.Data.Dto;
using CinemaApp.Helpers;
using CinemaApp.Interfaces;
using CinemaApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CinemaApp.Controllers
{

    [Authorize]
    public class MoviesController : Controller
    {
        private readonly IMovies _movies;
        private readonly IPhotoService _photoService;
        private readonly UserManager<AppUser> _userManager;

        //private readonly ApplicationDbContext _context;
        

        //In the Constructor we had the ApplicationDbContext
        public MoviesController( IMovies movies, IPhotoService photoService,UserManager<AppUser> userManager)
        {
            //_context = context;
            _movies = movies;
            _photoService = photoService;
            _userManager = userManager;
        }


        //This Index is for the Pagiantion
        public async Task<IActionResult> Index(int pg=1)
        {
            //var Movies=_context.Movies.ToList();
            var (Movies,p)= await _movies.Index(pg);
            ViewBag.Pager = p;
            return View(Movies);
        }

        public async Task<IActionResult> Details(int id)
        {
            //We are using the Repo and getting Back A View Model that we made (for passing to the View both List and also Single Movie) 
            //We mostly care about the Specific movie thats why we are only ckecking one attribut of the ModelView
            var DetailedMovie= await _movies.GetMovieById(id);
            var RelatedMovies=await _movies.GetRelatedMovies(id);
            if (DetailedMovie != null)
            {
                var MovieDetailViewModel = new MovieDetailDto
                {
                    MyMovie = DetailedMovie,
                    MoreMoviesM = RelatedMovies,
                    Reviews = DetailedMovie.Reviews

                };
                return View(MovieDetailViewModel);
            }
            return NotFound();
            
        }


        public async Task<IActionResult> Create()
        {
           
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(MovieCreateDto movies)
        {
           
            if (ModelState.IsValid)
            {
                var userid = _userManager.GetUserId(User);
                var result = await _photoService.AddPhotoAsync(movies.Image);
                var movie = new Movies
                {
                    Title = movies.Title,
                    Description = movies.Description,
                    Image = result.Url.ToString(),
                    Categories = movies.Categories,
                    AppUserId=userid
                };
                _movies.Add(movie);
                return RedirectToAction("Index");
            }
            
            return View(movies);
           
        }

        public async Task<IActionResult> Edit(int id)
        {
            var movie=await _movies.GetMovieById(id);
            if (movie == null)
            {
                return NotFound();
            }
            var EditModel = new MovieEditDto
            {
                Id = movie.Id,
                Title = movie.Title,
                Description = movie.Description,
                URL = movie.Image,
                
                Categories = movie.Categories
            };
            return View(EditModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id,MovieEditDto movieEditDto)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Changes Could not be made Try Again");
                return View();
            }
            //var movie = await _movies.GetMovieById(id);
            var movie = await _movies.GetMovieByIdNoTrack(id);
            //_context.Entry(movie).State = EntityState.Detached; // Detach the original entity

            if (movie == null)
            {
                return NotFound();
            }
            else
            {
                try
                {
                    var imgcloudinary = await _photoService.DeletePhotoAsync(movie.Image);
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", "Could not delete the Photo");
                    return View();

                }
                var result = await _photoService.AddPhotoAsync(movieEditDto.Image);
                var NewMovie = new Movies
                {
                    Id = movieEditDto.Id,
                    Title = movieEditDto.Title,
                    Description = movieEditDto.Description,
                    Image = result.Url.ToString(),
                    Categories = movieEditDto.Categories,
                    AppUserId=_userManager.GetUserId(User),
                };
                
                _movies.Update(NewMovie);
                return RedirectToAction("Index");
            }
            
        }

        public async Task<IActionResult> Delete(int id)
        {
            var movie = await _movies.GetMovieById(id);
            if (movie == null)
            {
                return NotFound();
            }
            var DeleteModel = new MovieDeleteDto
            {
                Id = movie.Id,
                Title = movie.Title,
                Description = movie.Description,
                URL = movie.Image,
                Categories = movie.Categories
            };
            return View(DeleteModel);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id,MovieDeleteDto m)
        {
            var movie = await _movies.GetMovieById(id);
            if (movie == null)
            {
                return NotFound();
            }
            try
            {
                var imgcloudinary = await _photoService.DeletePhotoAsync(movie.Image);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Could not delete the Photo");
                return View();

            }
            _movies.Remove(movie);
            return RedirectToAction("Index");
        }



    }
}

CinemaApp/Controllers/UsersController.cs
using System.Security.Claims;
using System.Threading.Tasks;
using CinemaApp.Data.Dto;
using CinemaApp.Interfaces;
using CinemaApp.Models;
using CloudinaryDotNet.Actions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.EntityFrameworkCore;

namespace CinemaApp.Controllers
{
    [Authorize]
    public class UsersController : Controller
    {
        private readonly IUsers _users;
        private readonly UserManager<AppUser> _userManager;
        private readonly IHttpContextAccessor _contextAccessor;
        private readonly IPhotoService _photoService;

        public UsersController(IUsers users, UserManager<AppUser> userManager, IHttpContextAccessor contextAccessor, IPhotoService photoService)
        {
            _users = users;
            _userManager = userManager;
            _contextAccessor = contextAccessor;
            _photoService = photoService;
        }

        private void MapUserEdi(AppUser appuser, UserEditDto userEditDt, ImageUploadResult imageUploadResult)
        {
            appuser.Id = userEditDt.Id;
            appuser.FirstName = userEditDt.FirstName;
            appuser.LastName = userEditDt.LastName;
            appuser.ImagUrl = imageUploadResult.Url.ToString();
        }
        private void MapUserEditNoImage(AppUser appuser, UserEditDto userEditDt)
        {
            appuser.Id = userEditDt.Id;
            appuser.FirstName = userEditDt.FirstName;
            appuser.LastName = userEditDt.LastName;
            appuser.ImagUrl = null;

        }

        public async Task<IActionResult> Index(int pg = 1)
        {
            //var Movies=_context.Movies.ToList();
            var (AppUsers, p) = await _users.Index(pg);
            //In all the privious Indexes we were returning list but we were not using Dtos(we were dipslaying str8 the model)
            //Now we want to pass a list of Dtos in our model so we need for each on of the list of the users we are getting
            //to make the mapper with Dto and pass them 
            var AllUsers = new List<UsersIndexDto>();
            foreach (var user in AppUsers)
            {
                var DtoUser = new UsersIndexDto
                {
                    id = user.Id,
                    FirstName = user.FirstName,
                    LastName = user.LastName,
                    Username = user.UserName,
                    Img=user.ImagUrl
                };
                AllUsers.Add(DtoUser);
            }
            ViewBag.Pager = p;
            return View(AllUsers);
        }

        public async Task<IActionResult> Details(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            
            var movies = await _users.GetUsersMovies(id);
            var DetailUserDto = new UsersDetailDto
            {

                FirstName = user.FirstName,
                LastName = user.LastName,
                Username = user.UserName,
                Movies = movies,
                Img = user.ImagUrl
            };
            return View(DetailUserDto);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(string id,UserEditDto userEditDto)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("","Something went wrong Please try Again");
                return View(userEditDto);

            }
             
            var user = await _users.GetByIdNoTracking(userEditDto.Id);
            if (user == null)
            {
                return NotFound();
            }
            if(user.ImagUrl == null)
            {
                if (userEditDto.Image != null)
                {
                    var resulturl = await _photoService.AddPhotoAsync(userEditDto.Image);
                    //Using this because we are manipulating 2 AppUsers in the same function
                    MapUserEdi(user, userEditDto, resulturl);
                }
                else
                {
                    MapUserEditNoImage(user, userEditDto);
                }
                    await _users.UpdateAsync(user);
                return RedirectToAction("GetAllMovies", "Dashboard");

            }
            else
            {
                
                try
                {
                    var imgcloudinary = await _photoService.DeletePhotoAsync(user.ImagUrl);
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", "Could not delete the Photo");
                    return View();

                }
                if (userEditDto.Image != null )
                {
                    var resulturl = await _photoService.AddPhotoAsync(userEditDto.Image);
                    //Using this because we are manipulating 2 AppUsers in the same function
                    MapUserEdi(user, userEditDto, resulturl);
                }
                else
                {
                    MapUserEditNoImage(user, userEditDto);
                }
                await _users.UpdateAsync(user);
               
                return RedirectToAction("GetAllMovies","Dashboard");
                
            }
               
           
        }

        public async Task<IActionResult> Edit(string id)
        {
            //from here we are getting the users id from the http context  
            var cusreid = _contextAccessor.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var user=await _userManager.FindByIdAsync(cusreid);
            if (user == null)
            {
                return NotFound();
            }
            var UserDto = new UserEditDto
            {
                Id = user.Id,
                FirstName = user.FirstName,
                LastName = user.LastName,
                ImageUrl = user.ImagUrl
,
            };
            return View(UserDto);
        }

    }
}

CinemaApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MovieReviews</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Card.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CinemaApp.styles.css" asp-append-version="true" />
    @*<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">*@

    
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light bg-black shadow-sm border-bottom py-3">
            <div class="container-fluid">
                <a class="navbar-brand fw-bold text-primary" asp-area="" asp-controller="Home" asp-action="Index">
                    <h4 class="text-white">MovieReviews</h4>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent"
                        aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse justify-content-end" id="navbarContent">
                    <ul class="navbar-nav align-items-center gap-2">

                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="btn btn-outline-primary px-3" asp-area="" asp-controller="Dashboard" asp-action="GetAllMovies">
                                    Dashboard
                                </a>
                            </li>

                            <li class="nav-item">
                                <a class="btn btn-outline-primary px-3" asp-area="" asp-controller="Movies" asp-action="Index">
                                    Movies
                                </a>
                            </li>

                            <!-- For Listing all the Users -->
                            <li class="nav-item">
                                <a class="btn btn-outline-primary px-3" asp-area="" asp-controller="Users" asp-action="Index">
                                    Users
                                </a>
                            </li>
                            <!-- This one is for the Users -->

                            <li class="nav-item">
                                <a class="btn btn-outline-danger px-3" asp-area="" asp-controller="Account" asp-action="LogOut">
                                    Log Out
                                </a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="btn btn-outline-primary px-3" asp-area="" asp-controller="Account" asp-action="LogIn">
                                    Log In
                                </a>
                            </li>

                            <li class="nav-item">
                                <a class="btn btn-outline-primary px-3" asp-area="" asp-controller="Account" asp-action="SignUp">
                                    Sign Up
                                </a>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
       
    
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

   
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>